### ISSUE TITLE
Yield

### ISSUE THREAD

**Issue by IanaKhitsko** [perc3ptr0n/TTPS#10]
https://github.com/perc3ptr0n/TTPS/blob/0da5fdebc4b33ed611034cee8b458758c60ae1ff/lab_2_euro_diffusion/map.py#L157-L161

I'm not a python dev, but still - can we use yield for this case?

**Comment by perc3ptr0n** [comment]
Yield usually used to create generator object and return next object any time it's called until the end. Here i don't need to return any objects, so there is no need for yield construction.
