### ISSUE TITLE
Return instead of break

### ISSUE THREAD

**Issue by IanaKhitsko** [perc3ptr0n/TTPS#11]
https://github.com/perc3ptr0n/TTPS/blob/0da5fdebc4b33ed611034cee8b458758c60ae1ff/lab_2_euro_diffusion/map.py#L147-L150

you can just return herefor both cases, right?

**Comment by perc3ptr0n** [comment]
I don't think so. In this method i check all countries together, so i use these breaks to get out from checking of current country and go to next.
