### ISSUE TITLE
Replace numbers with named constants

### ISSUE THREAD

**Issue by romick101** [perc3ptr0n/TTPS#2]
https://github.com/perc3ptr0n/TTPS/blob/ed19e5ddf91b89be47fbab15ad71cf06d7858db4/lab_2_euro_diffusion/classes.py#L55

These numbers can be stored in the named constants like MIN_COORD and MAX_COORD

**Comment by perc3ptr0n** [comment]
Fixed. min_coord & max_coord constants created.
