### ISSUE TITLE
Bad identifier naming

### ISSUE THREAD

**Issue by romick101** [perc3ptr0n/TTPS#6]
https://github.com/perc3ptr0n/TTPS/blob/ed19e5ddf91b89be47fbab15ad71cf06d7858db4/lab_2_euro_diffusion/classes.py#L117

I'd suggest renaming city and coordinate identifiers to something like bottomLeftCity, topRightCity, bottomLeftX etc.

**Comment by perc3ptr0n** [comment]
Cities identifiers are used only as parameters in constructor. 
I don't sure, but in mathematical sense x1, x2 and y1, y2 are more clear and shorter than bottom/top/left/right.
