### ISSUE TITLE
Coordinate validations needed. 

### ISSUE THREAD

**Issue by romick101** [perc3ptr0n/TTPS#7]
https://github.com/perc3ptr0n/TTPS/blob/ed19e5ddf91b89be47fbab15ad71cf06d7858db4/lab_2_euro_diffusion/classes.py#L112

I don't see any coordinate checks for incoming cities. Without them there'll be potential problems with incorrect input like  top city located lower than bottom etc.

**Comment by perc3ptr0n** [comment]
Fixed. check_coords(x, y) method added to class Country.
