### ISSUE TITLE
Return condition

### ISSUE THREAD

**Issue by IanaKhitsko** [perc3ptr0n/TTPS#9]
https://github.com/perc3ptr0n/TTPS/blob/0da5fdebc4b33ed611034cee8b458758c60ae1ff/lab_2_euro_diffusion/map.py#L102-L105

return 0 <= x <= 9 and 0 <= y <= 9 and self.map[x][y] != 0

?

**Comment by perc3ptr0n** [comment]
I don't sure, but in my opinion few extra lines of code makes all construction more understandable)
